[package]
name = "simplecrawler"
version = "0.1.0"
authors = ["pkusensei"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
futures = "^0.3"
reqwest = "^0.10.8"
scraper = "^0.12"
tokio = { version = "^0.2", features = ["fs", "rt-threaded", "macros"] }

[profile.release]
lto = true